2025-01-25 08:24:02,645 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10666a4e0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,645 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106520530>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,647 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10658ff20>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,647 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10658f800>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,650 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104407050>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,650 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104405730>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,652 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=51664): Max retries exceeded with url: /session/2bbb52b65325103010e69e5d1ee922ec/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1044072c0>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 08:24:02,652 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=51634): Max retries exceeded with url: /session/e634d31ac5044156891874464f1c9890/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104421730>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 08:24:02,653 ERROR  Error while scraping channel info for @Jacksepticeye: 'dict' object has no attribute 'model_dump_json'
2025-01-25 08:24:02,653 ERROR  Error while scraping channel info for @Ninja: 'dict' object has no attribute 'model_dump_json'
2025-01-25 08:24:02,654 INFO  Scraping complete for @Jacksepticeye
2025-01-25 08:24:02,655 INFO  Scraping complete for @Ninja
2025-01-25 08:24:02,657 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10668f3b0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,657 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10668dc40>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,659 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10668cf80>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,659 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10668e030>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,661 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106520710>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,661 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10668e9c0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,664 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=51664): Max retries exceeded with url: /session/2bbb52b65325103010e69e5d1ee922ec/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1065209b0>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 08:24:02,664 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=51634): Max retries exceeded with url: /session/e634d31ac5044156891874464f1c9890/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106520830>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 08:24:02,665 ERROR  Error while scraping channel info for @Shroud: 'dict' object has no attribute 'model_dump_json'
2025-01-25 08:24:02,665 ERROR  Error while scraping channel info for @Pokimane: 'dict' object has no attribute 'model_dump_json'
2025-01-25 08:24:02,667 INFO  Scraping complete for @Shroud
2025-01-25 08:24:02,667 INFO  Scraping complete for @Pokimane
