2025-01-25 08:19:04,224 INFO  Fetching channel name and verification status.
2025-01-25 08:19:04,837 INFO  Clicking 'More' button to fetch about info.
2025-01-25 08:19:05,505 INFO  Fetching channel links.
2025-01-25 08:19:05,593 INFO  Fetching channel details (subscribers, videos, views, joined date).
2025-01-25 08:19:05,631 INFO  Closing channel details popup.
2025-01-25 08:19:05,663 INFO  Scraping complete for @JennaMarbles
2025-01-25 08:19:06,424 INFO  Fetching channel name and verification status.
2025-01-25 08:19:07,116 INFO  Clicking 'More' button to fetch about info.
2025-01-25 08:19:07,722 INFO  Fetching channel links.
2025-01-25 08:19:07,790 INFO  Fetching channel details (subscribers, videos, views, joined date).
2025-01-25 08:19:07,825 INFO  Closing channel details popup.
2025-01-25 08:19:07,855 INFO  Scraping complete for @LillySingh
2025-01-25 08:19:08,115 INFO  Fetching channel name and verification status.
2025-01-25 08:19:13,100 ERROR  Failed to fetch channel name and verification status.
2025-01-25 08:19:13,101 INFO  Clicking 'More' button to fetch about info.
2025-01-25 08:19:18,416 ERROR  Failed to fetch channel name and verification status.
2025-01-25 08:19:18,417 INFO  Clicking 'More' button to fetch about info.
2025-01-25 08:19:23,371 ERROR  Failed to fetch about info.
2025-01-25 08:19:23,371 INFO  Fetching channel links.
2025-01-25 08:19:28,703 ERROR  Failed to fetch about info.
2025-01-25 08:19:28,704 INFO  Fetching channel links.
2025-01-25 08:19:33,606 ERROR  Failed to fetch channel links.
2025-01-25 08:19:33,608 INFO  Fetching channel details (subscribers, videos, views, joined date).
2025-01-25 08:19:38,935 ERROR  Failed to fetch channel links.
2025-01-25 08:19:38,939 INFO  Fetching channel details (subscribers, videos, views, joined date).
2025-01-25 08:19:43,827 ERROR  Failed to fetch channel details section.
2025-01-25 08:19:43,828 INFO  Closing channel details popup.
2025-01-25 08:19:49,240 ERROR  Failed to fetch channel details section.
2025-01-25 08:19:49,241 INFO  Closing channel details popup.
2025-01-25 08:19:54,087 ERROR  Failed to close channel details popup.
2025-01-25 08:19:54,089 INFO  Scraping complete for @Nigahiga
2025-01-25 08:19:55,596 INFO  Fetching channel name and verification status.
2025-01-25 08:19:55,645 INFO  Clicking 'More' button to fetch about info.
2025-01-25 08:19:56,306 INFO  Fetching channel links.
2025-01-25 08:19:56,357 INFO  Fetching channel details (subscribers, videos, views, joined date).
2025-01-25 08:19:56,394 INFO  Closing channel details popup.
2025-01-25 08:19:56,427 INFO  Scraping complete for @DavidDobrik
2025-01-25 08:19:57,090 INFO  Fetching channel name and verification status.
2025-01-25 08:19:57,650 INFO  Clicking 'More' button to fetch about info.
2025-01-25 08:19:58,308 INFO  Fetching channel links.
2025-01-25 08:19:58,374 INFO  Fetching channel details (subscribers, videos, views, joined date).
2025-01-25 08:19:58,409 INFO  Closing channel details popup.
2025-01-25 08:19:58,437 INFO  Scraping complete for @JakePaul
2025-01-25 08:19:58,668 INFO  Fetching channel name and verification status.
2025-01-25 08:19:59,455 ERROR  Failed to close channel details popup.
2025-01-25 08:19:59,457 INFO  Scraping complete for @Zoella
2025-01-25 08:20:02,480 INFO  Fetching channel name and verification status.
2025-01-25 08:20:02,565 INFO  Clicking 'More' button to fetch about info.
2025-01-25 08:20:03,225 INFO  Fetching channel links.
2025-01-25 08:20:03,293 INFO  Fetching channel details (subscribers, videos, views, joined date).
2025-01-25 08:20:03,330 INFO  Closing channel details popup.
2025-01-25 08:20:03,362 INFO  Scraping complete for @RhettandLink
2025-01-25 08:20:04,301 INFO  Fetching channel name and verification status.
2025-01-25 08:20:04,493 INFO  Verification status: Not verified.
2025-01-25 08:20:04,494 INFO  Clicking 'More' button to fetch about info.
2025-01-25 08:20:05,093 INFO  Fetching channel links.
2025-01-25 08:20:05,128 INFO  Fetching channel details (subscribers, videos, views, joined date).
2025-01-25 08:20:05,180 ERROR  Failed to fetch videos count.
2025-01-25 08:20:05,191 ERROR  Failed to fetch views count.
2025-01-25 08:20:05,201 INFO  Closing channel details popup.
2025-01-25 08:20:05,254 INFO  Scraping complete for @TheTryGuys
2025-01-25 08:20:06,081 INFO  Fetching channel name and verification status.
2025-01-25 08:20:06,538 INFO  Clicking 'More' button to fetch about info.
2025-01-25 08:20:08,969 ERROR  Failed to fetch channel name and verification status.
2025-01-25 08:20:08,971 INFO  Clicking 'More' button to fetch about info.
2025-01-25 08:20:12,391 INFO  Fetching channel links.
2025-01-25 08:20:12,456 INFO  Fetching channel details (subscribers, videos, views, joined date).
2025-01-25 08:20:12,495 INFO  Closing channel details popup.
2025-01-25 08:20:12,531 INFO  Scraping complete for @PhilipDeFranco
2025-01-25 08:20:13,279 INFO  Fetching channel name and verification status.
2025-01-25 08:20:13,685 INFO  Clicking 'More' button to fetch about info.
2025-01-25 08:20:15,483 INFO  Fetching channel links.
2025-01-25 08:20:15,607 INFO  Fetching channel details (subscribers, videos, views, joined date).
2025-01-25 08:20:15,642 INFO  Closing channel details popup.
2025-01-25 08:20:15,678 INFO  Scraping complete for @FitnessBlender
2025-01-25 08:20:16,457 INFO  Fetching channel name and verification status.
2025-01-25 08:20:17,206 INFO  Clicking 'More' button to fetch about info.
2025-01-25 08:20:17,994 INFO  Fetching channel links.
2025-01-25 08:20:18,055 INFO  Fetching channel details (subscribers, videos, views, joined date).
2025-01-25 08:20:18,141 INFO  Closing channel details popup.
2025-01-25 08:20:18,221 INFO  Scraping complete for @MichellePhan
2025-01-25 08:20:19,054 INFO  Fetching channel name and verification status.
2025-01-25 08:20:19,415 ERROR  Failed to fetch about info.
2025-01-25 08:20:19,415 INFO  Fetching channel links.
2025-01-25 08:20:19,600 INFO  Clicking 'More' button to fetch about info.
2025-01-25 08:20:20,071 INFO  Fetching channel links.
2025-01-25 08:20:20,132 INFO  Fetching channel details (subscribers, videos, views, joined date).
2025-01-25 08:20:20,179 INFO  Closing channel details popup.
2025-01-25 08:20:20,214 INFO  Scraping complete for @Vsauce
2025-01-25 08:20:21,666 INFO  Fetching channel name and verification status.
2025-01-25 08:20:21,872 INFO  Clicking 'More' button to fetch about info.
2025-01-25 08:20:23,681 INFO  Fetching channel links.
2025-01-25 08:20:23,872 INFO  Fetching channel details (subscribers, videos, views, joined date).
2025-01-25 08:20:23,966 INFO  Closing channel details popup.
2025-01-25 08:20:24,047 INFO  Scraping complete for @Veritasium
2025-01-25 08:20:25,203 INFO  Fetching channel name and verification status.
2025-01-25 08:20:26,046 INFO  Clicking 'More' button to fetch about info.
2025-01-25 08:20:29,510 ERROR  Failed to fetch channel links.
2025-01-25 08:20:29,515 INFO  Fetching channel details (subscribers, videos, views, joined date).
2025-01-25 08:20:36,295 ERROR  Failed to fetch about info.
2025-01-25 08:20:36,302 INFO  Fetching channel links.
2025-01-25 08:20:36,331 INFO  Fetching channel details (subscribers, videos, views, joined date).
2025-01-25 08:20:36,376 INFO  Closing channel details popup.
2025-01-25 08:20:36,423 INFO  Scraping complete for @CGPGrey
2025-01-25 08:20:38,571 INFO  Fetching channel name and verification status.
2025-01-25 08:20:39,886 ERROR  Failed to fetch channel details section.
2025-01-25 08:20:39,886 INFO  Closing channel details popup.
2025-01-25 08:20:48,853 ERROR  Failed to fetch channel name and verification status.
2025-01-25 08:20:48,860 INFO  Clicking 'More' button to fetch about info.
2025-01-25 08:20:50,185 ERROR  Failed to close channel details popup.
2025-01-25 08:20:50,190 INFO  Scraping complete for @LoganPaul
2025-01-25 08:20:51,638 INFO  Fetching channel name and verification status.
2025-01-25 08:20:51,860 INFO  Clicking 'More' button to fetch about info.
2025-01-25 08:20:52,546 INFO  Fetching channel links.
2025-01-25 08:20:52,745 INFO  Fetching channel details (subscribers, videos, views, joined date).
2025-01-25 08:20:52,826 INFO  Closing channel details popup.
2025-01-25 08:20:52,894 INFO  Scraping complete for @Numberphile
2025-01-25 08:20:53,866 INFO  Fetching channel name and verification status.
2025-01-25 08:20:54,385 INFO  Clicking 'More' button to fetch about info.
2025-01-25 08:20:55,069 INFO  Fetching channel links.
2025-01-25 08:20:55,123 INFO  Fetching channel details (subscribers, videos, views, joined date).
2025-01-25 08:20:55,158 INFO  Closing channel details popup.
2025-01-25 08:20:55,191 INFO  Scraping complete for @MinutePhysics
2025-01-25 08:20:55,947 INFO  Fetching channel name and verification status.
2025-01-25 08:20:56,630 INFO  Clicking 'More' button to fetch about info.
2025-01-25 08:20:57,456 INFO  Fetching channel links.
2025-01-25 08:20:57,578 INFO  Fetching channel details (subscribers, videos, views, joined date).
2025-01-25 08:20:57,639 INFO  Closing channel details popup.
2025-01-25 08:20:57,707 INFO  Scraping complete for @CrashCourse
2025-01-25 08:20:58,504 INFO  Fetching channel name and verification status.
2025-01-25 08:20:59,119 INFO  Clicking 'More' button to fetch about info.
2025-01-25 08:20:59,325 ERROR  Failed to fetch about info.
2025-01-25 08:20:59,326 INFO  Fetching channel links.
2025-01-25 08:20:59,772 INFO  Fetching channel links.
2025-01-25 08:20:59,817 INFO  Fetching channel details (subscribers, videos, views, joined date).
2025-01-25 08:20:59,859 INFO  Closing channel details popup.
2025-01-25 08:20:59,890 INFO  Scraping complete for @ScienceChannel
2025-01-25 08:21:00,864 INFO  Fetching channel name and verification status.
2025-01-25 08:21:01,533 INFO  Clicking 'More' button to fetch about info.
2025-01-25 08:21:02,207 INFO  Fetching channel links.
2025-01-25 08:21:02,251 INFO  Fetching channel details (subscribers, videos, views, joined date).
2025-01-25 08:21:02,288 INFO  Closing channel details popup.
2025-01-25 08:21:02,322 INFO  Scraping complete for @AsapSCIENCE
2025-01-25 08:21:02,561 INFO  Fetching channel name and verification status.
2025-01-25 08:21:09,714 ERROR  Failed to fetch channel links.
2025-01-25 08:21:09,720 INFO  Fetching channel details (subscribers, videos, views, joined date).
2025-01-25 08:21:12,853 ERROR  Failed to fetch channel name and verification status.
2025-01-25 08:21:12,856 INFO  Clicking 'More' button to fetch about info.
2025-01-25 08:21:20,060 ERROR  Failed to fetch channel details section.
2025-01-25 08:21:20,064 INFO  Closing channel details popup.
2025-01-25 08:21:23,234 ERROR  Failed to fetch about info.
2025-01-25 08:21:23,236 INFO  Fetching channel links.
2025-01-25 08:21:30,365 ERROR  Failed to close channel details popup.
2025-01-25 08:21:30,376 INFO  Scraping complete for @TEDxTalks
2025-01-25 08:21:30,909 INFO  Fetching channel name and verification status.
2025-01-25 08:21:33,501 ERROR  Failed to fetch channel links.
2025-01-25 08:21:33,503 INFO  Fetching channel details (subscribers, videos, views, joined date).
2025-01-25 08:21:41,222 ERROR  Failed to fetch channel name and verification status.
2025-01-25 08:21:41,230 INFO  Clicking 'More' button to fetch about info.
2025-01-25 08:21:43,800 ERROR  Failed to fetch channel details section.
2025-01-25 08:21:43,801 INFO  Closing channel details popup.
2025-01-25 08:21:51,553 ERROR  Failed to fetch about info.
2025-01-25 08:21:51,554 INFO  Fetching channel links.
2025-01-25 08:21:54,235 ERROR  Failed to close channel details popup.
2025-01-25 08:21:54,242 INFO  Scraping complete for @NationalGeographic
2025-01-25 08:21:55,277 INFO  Fetching channel name and verification status.
2025-01-25 08:22:01,487 INFO  Clicking 'More' button to fetch about info.
2025-01-25 08:22:02,005 ERROR  Failed to fetch channel links.
2025-01-25 08:22:02,007 INFO  Fetching channel details (subscribers, videos, views, joined date).
2025-01-25 08:22:11,835 ERROR  Failed to fetch about info.
2025-01-25 08:22:11,841 INFO  Fetching channel links.
2025-01-25 08:22:12,297 ERROR  Failed to fetch channel details section.
2025-01-25 08:22:12,297 INFO  Closing channel details popup.
2025-01-25 08:22:22,096 ERROR  Failed to fetch channel links.
2025-01-25 08:22:22,124 INFO  Fetching channel details (subscribers, videos, views, joined date).
2025-01-25 08:22:22,572 ERROR  Failed to close channel details popup.
2025-01-25 08:22:22,575 INFO  Scraping complete for @DiscoveryChannel
2025-01-25 08:22:23,466 INFO  Fetching channel name and verification status.
2025-01-25 08:22:23,573 INFO  Verification status: Not verified.
2025-01-25 08:22:23,574 INFO  Clicking 'More' button to fetch about info.
2025-01-25 08:22:32,531 ERROR  Failed to fetch channel details section.
2025-01-25 08:22:32,535 INFO  Closing channel details popup.
2025-01-25 08:22:32,564 ERROR  Webdriver Exception: Message: element not interactable
  (Session info: chrome=131.0.6778.265)
Stacktrace:
0   chromedriver                        0x00000001035ce138 cxxbridge1$str$ptr + 3653888
1   chromedriver                        0x00000001035c6988 cxxbridge1$str$ptr + 3623248
2   chromedriver                        0x000000010302c7d8 cxxbridge1$string$len + 88828
3   chromedriver                        0x0000000103071cf0 cxxbridge1$string$len + 372756
4   chromedriver                        0x0000000103067470 cxxbridge1$string$len + 329620
5   chromedriver                        0x0000000103066ec4 cxxbridge1$string$len + 328168
6   chromedriver                        0x00000001030aa4f0 cxxbridge1$string$len + 604180
7   chromedriver                        0x0000000103065564 cxxbridge1$string$len + 321672
8   chromedriver                        0x00000001030661b4 cxxbridge1$string$len + 324824
9   chromedriver                        0x0000000103598fc0 cxxbridge1$str$ptr + 3436424
10  chromedriver                        0x000000010359c2dc cxxbridge1$str$ptr + 3449508
11  chromedriver                        0x000000010357fe60 cxxbridge1$str$ptr + 3333672
12  chromedriver                        0x000000010359cb9c cxxbridge1$str$ptr + 3451748
13  chromedriver                        0x0000000103571678 cxxbridge1$str$ptr + 3274304
14  chromedriver                        0x00000001035b72b4 cxxbridge1$str$ptr + 3560060
15  chromedriver                        0x00000001035b7430 cxxbridge1$str$ptr + 3560440
16  chromedriver                        0x00000001035c65fc cxxbridge1$str$ptr + 3622340
17  libsystem_pthread.dylib             0x00000001885e32e4 _pthread_start + 136
18  libsystem_pthread.dylib             0x00000001885de0fc thread_start + 8

2025-01-25 08:22:32,565 ERROR  Error while scraping channel info for @BraveWilderness: 'dict' object has no attribute 'model_dump_json'
2025-01-25 08:22:32,566 INFO  Scraping complete for @BraveWilderness
2025-01-25 08:22:33,664 INFO  Fetching channel name and verification status.
2025-01-25 08:22:34,005 ERROR  Failed to fetch about info.
2025-01-25 08:22:34,006 INFO  Fetching channel links.
2025-01-25 08:22:43,930 ERROR  Failed to fetch channel name and verification status.
2025-01-25 08:22:43,936 INFO  Clicking 'More' button to fetch about info.
2025-01-25 08:22:44,313 ERROR  Failed to fetch channel links.
2025-01-25 08:22:44,314 INFO  Fetching channel details (subscribers, videos, views, joined date).
2025-01-25 08:22:54,646 ERROR  Failed to fetch channel details section.
2025-01-25 08:22:54,651 INFO  Closing channel details popup.
2025-01-25 08:22:54,666 ERROR  Webdriver Exception: Message: element not interactable
  (Session info: chrome=131.0.6778.265)
Stacktrace:
0   chromedriver                        0x00000001047b2138 cxxbridge1$str$ptr + 3653888
1   chromedriver                        0x00000001047aa988 cxxbridge1$str$ptr + 3623248
2   chromedriver                        0x00000001042107d8 cxxbridge1$string$len + 88828
3   chromedriver                        0x0000000104255cf0 cxxbridge1$string$len + 372756
4   chromedriver                        0x000000010424b470 cxxbridge1$string$len + 329620
5   chromedriver                        0x000000010424aec4 cxxbridge1$string$len + 328168
6   chromedriver                        0x000000010428e4f0 cxxbridge1$string$len + 604180
7   chromedriver                        0x0000000104249564 cxxbridge1$string$len + 321672
8   chromedriver                        0x000000010424a1b4 cxxbridge1$string$len + 324824
9   chromedriver                        0x000000010477cfc0 cxxbridge1$str$ptr + 3436424
10  chromedriver                        0x00000001047802dc cxxbridge1$str$ptr + 3449508
11  chromedriver                        0x0000000104763e60 cxxbridge1$str$ptr + 3333672
12  chromedriver                        0x0000000104780b9c cxxbridge1$str$ptr + 3451748
13  chromedriver                        0x0000000104755678 cxxbridge1$str$ptr + 3274304
14  chromedriver                        0x000000010479b2b4 cxxbridge1$str$ptr + 3560060
15  chromedriver                        0x000000010479b430 cxxbridge1$str$ptr + 3560440
16  chromedriver                        0x00000001047aa5fc cxxbridge1$str$ptr + 3622340
17  libsystem_pthread.dylib             0x00000001885e32e4 _pthread_start + 136
18  libsystem_pthread.dylib             0x00000001885de0fc thread_start + 8

2025-01-25 08:22:54,667 ERROR  Error while scraping channel info for @BrightSide: 'dict' object has no attribute 'model_dump_json'
2025-01-25 08:22:54,667 INFO  Scraping complete for @BrightSide
2025-01-25 08:22:54,796 ERROR  Failed to fetch about info.
2025-01-25 08:22:54,797 INFO  Fetching channel links.
2025-01-25 08:22:55,599 INFO  Fetching channel name and verification status.
2025-01-25 08:22:57,317 INFO  Clicking 'More' button to fetch about info.
2025-01-25 08:23:05,085 ERROR  Failed to fetch channel links.
2025-01-25 08:23:05,091 INFO  Fetching channel details (subscribers, videos, views, joined date).
2025-01-25 08:23:07,694 ERROR  Failed to fetch about info.
2025-01-25 08:23:07,695 INFO  Fetching channel links.
2025-01-25 08:23:15,441 ERROR  Failed to fetch channel details section.
2025-01-25 08:23:15,444 INFO  Closing channel details popup.
2025-01-25 08:23:15,493 ERROR  Webdriver Exception: Message: element not interactable
  (Session info: chrome=131.0.6778.265)
Stacktrace:
0   chromedriver                        0x00000001035ce138 cxxbridge1$str$ptr + 3653888
1   chromedriver                        0x00000001035c6988 cxxbridge1$str$ptr + 3623248
2   chromedriver                        0x000000010302c7d8 cxxbridge1$string$len + 88828
3   chromedriver                        0x0000000103071cf0 cxxbridge1$string$len + 372756
4   chromedriver                        0x0000000103067470 cxxbridge1$string$len + 329620
5   chromedriver                        0x0000000103066ec4 cxxbridge1$string$len + 328168
6   chromedriver                        0x00000001030aa4f0 cxxbridge1$string$len + 604180
7   chromedriver                        0x0000000103065564 cxxbridge1$string$len + 321672
8   chromedriver                        0x00000001030661b4 cxxbridge1$string$len + 324824
9   chromedriver                        0x0000000103598fc0 cxxbridge1$str$ptr + 3436424
10  chromedriver                        0x000000010359c2dc cxxbridge1$str$ptr + 3449508
11  chromedriver                        0x000000010357fe60 cxxbridge1$str$ptr + 3333672
12  chromedriver                        0x000000010359cb9c cxxbridge1$str$ptr + 3451748
13  chromedriver                        0x0000000103571678 cxxbridge1$str$ptr + 3274304
14  chromedriver                        0x00000001035b72b4 cxxbridge1$str$ptr + 3560060
15  chromedriver                        0x00000001035b7430 cxxbridge1$str$ptr + 3560440
16  chromedriver                        0x00000001035c65fc cxxbridge1$str$ptr + 3622340
17  libsystem_pthread.dylib             0x00000001885e32e4 _pthread_start + 136
18  libsystem_pthread.dylib             0x00000001885de0fc thread_start + 8

2025-01-25 08:23:15,494 ERROR  Error while scraping channel info for @TechLinked: 'dict' object has no attribute 'model_dump_json'
2025-01-25 08:23:15,495 INFO  Scraping complete for @TechLinked
2025-01-25 08:23:18,022 ERROR  Failed to fetch channel links.
2025-01-25 08:23:18,023 INFO  Fetching channel details (subscribers, videos, views, joined date).
2025-01-25 08:23:18,025 INFO  Fetching channel name and verification status.
2025-01-25 08:23:28,347 ERROR  Failed to fetch channel name and verification status.
2025-01-25 08:23:28,348 ERROR  Failed to fetch channel details section.
2025-01-25 08:23:28,354 INFO  Clicking 'More' button to fetch about info.
2025-01-25 08:23:28,354 INFO  Closing channel details popup.
2025-01-25 08:23:28,379 ERROR  Webdriver Exception: Message: element not interactable
  (Session info: chrome=131.0.6778.265)
Stacktrace:
0   chromedriver                        0x00000001047b2138 cxxbridge1$str$ptr + 3653888
1   chromedriver                        0x00000001047aa988 cxxbridge1$str$ptr + 3623248
2   chromedriver                        0x00000001042107d8 cxxbridge1$string$len + 88828
3   chromedriver                        0x0000000104255cf0 cxxbridge1$string$len + 372756
4   chromedriver                        0x000000010424b470 cxxbridge1$string$len + 329620
5   chromedriver                        0x000000010424aec4 cxxbridge1$string$len + 328168
6   chromedriver                        0x000000010428e4f0 cxxbridge1$string$len + 604180
7   chromedriver                        0x0000000104249564 cxxbridge1$string$len + 321672
8   chromedriver                        0x000000010424a1b4 cxxbridge1$string$len + 324824
9   chromedriver                        0x000000010477cfc0 cxxbridge1$str$ptr + 3436424
10  chromedriver                        0x00000001047802dc cxxbridge1$str$ptr + 3449508
11  chromedriver                        0x0000000104763e60 cxxbridge1$str$ptr + 3333672
12  chromedriver                        0x0000000104780b9c cxxbridge1$str$ptr + 3451748
13  chromedriver                        0x0000000104755678 cxxbridge1$str$ptr + 3274304
14  chromedriver                        0x000000010479b2b4 cxxbridge1$str$ptr + 3560060
15  chromedriver                        0x000000010479b430 cxxbridge1$str$ptr + 3560440
16  chromedriver                        0x00000001047aa5fc cxxbridge1$str$ptr + 3622340
17  libsystem_pthread.dylib             0x00000001885e32e4 _pthread_start + 136
18  libsystem_pthread.dylib             0x00000001885de0fc thread_start + 8

2025-01-25 08:23:28,381 ERROR  Error while scraping channel info for @UnboxTherapy: 'dict' object has no attribute 'model_dump_json'
2025-01-25 08:23:28,381 INFO  Scraping complete for @UnboxTherapy
2025-01-25 08:23:29,355 INFO  Fetching channel name and verification status.
2025-01-25 08:23:31,442 INFO  Clicking 'More' button to fetch about info.
2025-01-25 08:23:36,308 INFO  Fetching channel links.
2025-01-25 08:23:36,390 INFO  Fetching channel details (subscribers, videos, views, joined date).
2025-01-25 08:23:36,434 INFO  Closing channel details popup.
2025-01-25 08:23:36,469 INFO  Scraping complete for @AustinEvans
2025-01-25 08:23:37,312 INFO  Fetching channel name and verification status.
2025-01-25 08:23:37,730 INFO  Clicking 'More' button to fetch about info.
2025-01-25 08:23:38,649 ERROR  Failed to fetch about info.
2025-01-25 08:23:38,650 INFO  Fetching channel links.
2025-01-25 08:23:39,915 INFO  Fetching channel links.
2025-01-25 08:23:39,987 INFO  Fetching channel details (subscribers, videos, views, joined date).
2025-01-25 08:23:40,021 INFO  Closing channel details popup.
2025-01-25 08:23:40,052 INFO  Scraping complete for @LinusTechTips
2025-01-25 08:23:40,733 INFO  Fetching channel name and verification status.
2025-01-25 08:23:41,318 INFO  Clicking 'More' button to fetch about info.
2025-01-25 08:23:41,962 INFO  Fetching channel links.
2025-01-25 08:23:42,024 INFO  Fetching channel details (subscribers, videos, views, joined date).
2025-01-25 08:23:42,061 INFO  Closing channel details popup.
2025-01-25 08:23:42,090 INFO  Scraping complete for @JerryRigEverything
2025-01-25 08:23:43,384 INFO  Fetching channel name and verification status.
2025-01-25 08:23:43,615 INFO  Clicking 'More' button to fetch about info.
2025-01-25 08:23:44,282 INFO  Fetching channel links.
2025-01-25 08:23:44,369 INFO  Fetching channel details (subscribers, videos, views, joined date).
2025-01-25 08:23:44,414 INFO  Closing channel details popup.
2025-01-25 08:23:44,451 INFO  Scraping complete for @SuperSaf
2025-01-25 08:23:45,148 INFO  Fetching channel name and verification status.
2025-01-25 08:23:45,931 INFO  Clicking 'More' button to fetch about info.
2025-01-25 08:23:46,578 INFO  Fetching channel links.
2025-01-25 08:23:46,678 INFO  Fetching channel details (subscribers, videos, views, joined date).
2025-01-25 08:23:46,715 INFO  Closing channel details popup.
2025-01-25 08:23:46,750 INFO  Scraping complete for @TheVerge
2025-01-25 08:23:46,990 INFO  Fetching channel name and verification status.
2025-01-25 08:23:48,963 ERROR  Failed to fetch channel links.
2025-01-25 08:23:48,964 INFO  Fetching channel details (subscribers, videos, views, joined date).
2025-01-25 08:23:57,264 ERROR  Failed to fetch channel name and verification status.
2025-01-25 08:23:57,268 INFO  Clicking 'More' button to fetch about info.
2025-01-25 08:23:59,320 ERROR  Failed to fetch channel details section.
2025-01-25 08:23:59,322 INFO  Closing channel details popup.
2025-01-25 08:24:02,391 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10666a750>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/element
2025-01-25 08:24:02,392 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104405190>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/element
2025-01-25 08:24:02,393 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104405490>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/element
2025-01-25 08:24:02,394 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=51664): Max retries exceeded with url: /session/2bbb52b65325103010e69e5d1ee922ec/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104405670>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 08:24:02,394 ERROR  Error while scraping channel info for @DaveLee: 'dict' object has no attribute 'model_dump_json'
2025-01-25 08:24:02,394 INFO  Scraping complete for @DaveLee
2025-01-25 08:24:02,396 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104405ac0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,397 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104308410>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,398 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104404fb0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,399 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=51664): Max retries exceeded with url: /session/2bbb52b65325103010e69e5d1ee922ec/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1044056a0>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 08:24:02,399 ERROR  Error while scraping channel info for @JimmyKimmelLive: 'dict' object has no attribute 'model_dump_json'
2025-01-25 08:24:02,400 INFO  Scraping complete for @JimmyKimmelLive
2025-01-25 08:24:02,401 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104405070>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,402 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104405cd0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,403 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104405eb0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,404 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=51664): Max retries exceeded with url: /session/2bbb52b65325103010e69e5d1ee922ec/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1044060c0>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 08:24:02,404 ERROR  Error while scraping channel info for @TheTonightShow: 'dict' object has no attribute 'model_dump_json'
2025-01-25 08:24:02,404 INFO  Scraping complete for @TheTonightShow
2025-01-25 08:24:02,405 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104406480>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,406 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104406660>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,407 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104406840>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,408 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=51664): Max retries exceeded with url: /session/2bbb52b65325103010e69e5d1ee922ec/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104406a20>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 08:24:02,408 ERROR  Error while scraping channel info for @LateNightSeth: 'dict' object has no attribute 'model_dump_json'
2025-01-25 08:24:02,409 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106669550>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/element
2025-01-25 08:24:02,409 INFO  Scraping complete for @LateNightSeth
2025-01-25 08:24:02,411 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104406ea0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/element
2025-01-25 08:24:02,411 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104407290>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,412 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10668ce90>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/element
2025-01-25 08:24:02,412 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10668c830>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,413 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=51634): Max retries exceeded with url: /session/e634d31ac5044156891874464f1c9890/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104407410>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 08:24:02,413 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104406600>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,414 ERROR  Error while scraping channel info for @TheLateShow: 'dict' object has no attribute 'model_dump_json'
2025-01-25 08:24:02,415 INFO  Scraping complete for @TheLateShow
2025-01-25 08:24:02,415 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=51664): Max retries exceeded with url: /session/2bbb52b65325103010e69e5d1ee922ec/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104406ab0>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 08:24:02,416 ERROR  Error while scraping channel info for @Netflix: 'dict' object has no attribute 'model_dump_json'
2025-01-25 08:24:02,416 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104406510>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,416 INFO  Scraping complete for @Netflix
2025-01-25 08:24:02,417 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104405100>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,418 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104405eb0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,419 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104405c40>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,419 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104405190>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,420 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=51634): Max retries exceeded with url: /session/e634d31ac5044156891874464f1c9890/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104405400>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 08:24:02,421 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104404ec0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,421 ERROR  Error while scraping channel info for @HBO: 'dict' object has no attribute 'model_dump_json'
2025-01-25 08:24:02,422 INFO  Scraping complete for @HBO
2025-01-25 08:24:02,422 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=51664): Max retries exceeded with url: /session/2bbb52b65325103010e69e5d1ee922ec/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104407440>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 08:24:02,423 ERROR  Error while scraping channel info for @PrimeVideo: 'dict' object has no attribute 'model_dump_json'
2025-01-25 08:24:02,424 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104407830>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,424 INFO  Scraping complete for @PrimeVideo
2025-01-25 08:24:02,425 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10668d250>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,425 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10668cec0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,427 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104407590>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,427 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104405a30>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,428 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104406300>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,429 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=51634): Max retries exceeded with url: /session/e634d31ac5044156891874464f1c9890/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104405b20>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 08:24:02,429 ERROR  Error while scraping channel info for @GameTheory: 'dict' object has no attribute 'model_dump_json'
2025-01-25 08:24:02,430 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=51664): Max retries exceeded with url: /session/2bbb52b65325103010e69e5d1ee922ec/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104405400>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 08:24:02,430 INFO  Scraping complete for @GameTheory
2025-01-25 08:24:02,431 ERROR  Error while scraping channel info for @MatPatGT: 'dict' object has no attribute 'model_dump_json'
2025-01-25 08:24:02,431 INFO  Scraping complete for @MatPatGT
2025-01-25 08:24:02,432 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104404e60>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,433 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104406510>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,433 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104407110>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,434 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104406a80>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,434 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104406600>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,436 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104406330>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,436 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=51634): Max retries exceeded with url: /session/e634d31ac5044156891874464f1c9890/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104406ed0>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 08:24:02,437 ERROR  Error while scraping channel info for @FilmTheory: 'dict' object has no attribute 'model_dump_json'
2025-01-25 08:24:02,437 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=51664): Max retries exceeded with url: /session/2bbb52b65325103010e69e5d1ee922ec/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104407a70>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 08:24:02,438 INFO  Scraping complete for @FilmTheory
2025-01-25 08:24:02,438 ERROR  Error while scraping channel info for @ScreenJunkies: 'dict' object has no attribute 'model_dump_json'
2025-01-25 08:24:02,439 INFO  Scraping complete for @ScreenJunkies
2025-01-25 08:24:02,439 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10668cec0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,441 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1044053d0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,441 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104406720>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,442 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104406de0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,442 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104407110>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,444 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=51634): Max retries exceeded with url: /session/e634d31ac5044156891874464f1c9890/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104405ca0>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 08:24:02,444 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104405190>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,445 ERROR  Error while scraping channel info for @CinemaSins: 'dict' object has no attribute 'model_dump_json'
2025-01-25 08:24:02,445 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=51664): Max retries exceeded with url: /session/2bbb52b65325103010e69e5d1ee922ec/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104405ac0>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 08:24:02,445 INFO  Scraping complete for @CinemaSins
2025-01-25 08:24:02,446 ERROR  Error while scraping channel info for @PitchMeeting: 'dict' object has no attribute 'model_dump_json'
2025-01-25 08:24:02,447 INFO  Scraping complete for @PitchMeeting
2025-01-25 08:24:02,447 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104405c10>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,449 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104407f80>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,449 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104407e00>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,450 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1044203b0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,450 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104420230>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,452 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=51634): Max retries exceeded with url: /session/e634d31ac5044156891874464f1c9890/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104420770>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 08:24:02,452 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1044205f0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,453 ERROR  Error while scraping channel info for @ScreenRant: 'dict' object has no attribute 'model_dump_json'
2025-01-25 08:24:02,454 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=51664): Max retries exceeded with url: /session/2bbb52b65325103010e69e5d1ee922ec/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104406ea0>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 08:24:02,454 INFO  Scraping complete for @ScreenRant
2025-01-25 08:24:02,455 ERROR  Error while scraping channel info for @WatchMojo: 'dict' object has no attribute 'model_dump_json'
2025-01-25 08:24:02,455 INFO  Scraping complete for @WatchMojo
2025-01-25 08:24:02,456 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104405a60>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,457 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1044059a0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,457 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104406e70>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,459 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10668d880>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,459 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10668ce30>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,460 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=51634): Max retries exceeded with url: /session/e634d31ac5044156891874464f1c9890/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10668ce90>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 08:24:02,460 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104420710>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,461 ERROR  Error while scraping channel info for @Top10s: 'dict' object has no attribute 'model_dump_json'
2025-01-25 08:24:02,462 INFO  Scraping complete for @Top10s
2025-01-25 08:24:02,462 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=51664): Max retries exceeded with url: /session/2bbb52b65325103010e69e5d1ee922ec/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104420a70>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 08:24:02,463 ERROR  Error while scraping channel info for @EpicMealTime: 'dict' object has no attribute 'model_dump_json'
2025-01-25 08:24:02,464 INFO  Scraping complete for @EpicMealTime
2025-01-25 08:24:02,464 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104420e30>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,465 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104421400>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,466 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1044215e0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,466 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104421130>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,468 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10668cec0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,468 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10668ff20>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,469 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=51664): Max retries exceeded with url: /session/2bbb52b65325103010e69e5d1ee922ec/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10668d8b0>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 08:24:02,469 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=51634): Max retries exceeded with url: /session/e634d31ac5044156891874464f1c9890/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1044074d0>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 08:24:02,470 ERROR  Error while scraping channel info for @SortedFood: 'dict' object has no attribute 'model_dump_json'
2025-01-25 08:24:02,470 ERROR  Error while scraping channel info for @BingingWithBabish: 'dict' object has no attribute 'model_dump_json'
2025-01-25 08:24:02,471 INFO  Scraping complete for @SortedFood
2025-01-25 08:24:02,471 INFO  Scraping complete for @BingingWithBabish
2025-01-25 08:24:02,473 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104407980>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,473 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1044078f0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,475 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104420a70>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,475 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104421280>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,477 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104421760>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,477 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1044205c0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,479 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=51664): Max retries exceeded with url: /session/2bbb52b65325103010e69e5d1ee922ec/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104421b50>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 08:24:02,479 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=51634): Max retries exceeded with url: /session/e634d31ac5044156891874464f1c9890/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1044219d0>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 08:24:02,480 ERROR  Error while scraping channel info for @Tasty: 'dict' object has no attribute 'model_dump_json'
2025-01-25 08:24:02,480 ERROR  Error while scraping channel info for @BonAppetit: 'dict' object has no attribute 'model_dump_json'
2025-01-25 08:24:02,481 INFO  Scraping complete for @Tasty
2025-01-25 08:24:02,481 INFO  Scraping complete for @BonAppetit
2025-01-25 08:24:02,484 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10658c140>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,484 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104422030>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,485 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104421a00>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,485 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104421940>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,487 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104420920>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,487 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1044204a0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,489 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=51664): Max retries exceeded with url: /session/2bbb52b65325103010e69e5d1ee922ec/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104420aa0>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 08:24:02,489 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=51634): Max retries exceeded with url: /session/e634d31ac5044156891874464f1c9890/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104405b20>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 08:24:02,490 ERROR  Error while scraping channel info for @GordonRamsay: 'dict' object has no attribute 'model_dump_json'
2025-01-25 08:24:02,490 ERROR  Error while scraping channel info for @JoshuaWeissman: 'dict' object has no attribute 'model_dump_json'
2025-01-25 08:24:02,491 INFO  Scraping complete for @GordonRamsay
2025-01-25 08:24:02,491 INFO  Scraping complete for @JoshuaWeissman
2025-01-25 08:24:02,493 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104406ed0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,493 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10668df40>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,495 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10668d610>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,495 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10668d880>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,497 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10658c260>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,497 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10668c7d0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,499 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=51634): Max retries exceeded with url: /session/e634d31ac5044156891874464f1c9890/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10658ee70>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 08:24:02,499 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=51664): Max retries exceeded with url: /session/2bbb52b65325103010e69e5d1ee922ec/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10658f650>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 08:24:02,500 ERROR  Error while scraping channel info for @AlmazanKitchen: 'dict' object has no attribute 'model_dump_json'
2025-01-25 08:24:02,500 ERROR  Error while scraping channel info for @RosannaPansino: 'dict' object has no attribute 'model_dump_json'
2025-01-25 08:24:02,501 INFO  Scraping complete for @AlmazanKitchen
2025-01-25 08:24:02,501 INFO  Scraping complete for @RosannaPansino
2025-01-25 08:24:02,503 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10658f920>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,503 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10668cf80>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,504 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10668cec0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,504 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10668d880>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,506 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1044078f0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,507 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10668dcd0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,508 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=51634): Max retries exceeded with url: /session/e634d31ac5044156891874464f1c9890/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104407230>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 08:24:02,508 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=51664): Max retries exceeded with url: /session/2bbb52b65325103010e69e5d1ee922ec/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104405970>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 08:24:02,509 ERROR  Error while scraping channel info for @JamieOliver: 'dict' object has no attribute 'model_dump_json'
2025-01-25 08:24:02,509 ERROR  Error while scraping channel info for @BuzzFeed: 'dict' object has no attribute 'model_dump_json'
2025-01-25 08:24:02,510 INFO  Scraping complete for @JamieOliver
2025-01-25 08:24:02,510 INFO  Scraping complete for @BuzzFeed
2025-01-25 08:24:02,512 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104421250>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,512 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104421b80>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,514 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10658dee0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,514 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104421850>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,516 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10658f4a0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,516 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10658ef90>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,518 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=51634): Max retries exceeded with url: /session/e634d31ac5044156891874464f1c9890/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10658fc50>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 08:24:02,518 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=51664): Max retries exceeded with url: /session/2bbb52b65325103010e69e5d1ee922ec/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10658fdd0>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 08:24:02,519 ERROR  Error while scraping channel info for @Cut: 'dict' object has no attribute 'model_dump_json'
2025-01-25 08:24:02,519 ERROR  Error while scraping channel info for @Jubilee: 'dict' object has no attribute 'model_dump_json'
2025-01-25 08:24:02,520 INFO  Scraping complete for @Cut
2025-01-25 08:24:02,520 INFO  Scraping complete for @Jubilee
2025-01-25 08:24:02,522 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104421610>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,522 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104421160>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,524 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104421310>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,524 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104420e30>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,526 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1044207d0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,526 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104420230>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,528 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=51634): Max retries exceeded with url: /session/e634d31ac5044156891874464f1c9890/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10666a4e0>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 08:24:02,528 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=51664): Max retries exceeded with url: /session/2bbb52b65325103010e69e5d1ee922ec/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104420200>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 08:24:02,529 ERROR  Error while scraping channel info for @YesTheory: 'dict' object has no attribute 'model_dump_json'
2025-01-25 08:24:02,529 ERROR  Error while scraping channel info for @BeastReacts: 'dict' object has no attribute 'model_dump_json'
2025-01-25 08:24:02,531 INFO  Scraping complete for @YesTheory
2025-01-25 08:24:02,531 INFO  Scraping complete for @BeastReacts
2025-01-25 08:24:02,533 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1044053d0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,533 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104407cb0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,535 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104405c10>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,535 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104407530>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,537 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104406960>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,537 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104406840>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,539 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=51634): Max retries exceeded with url: /session/e634d31ac5044156891874464f1c9890/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1044218e0>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 08:24:02,539 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=51664): Max retries exceeded with url: /session/2bbb52b65325103010e69e5d1ee922ec/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1044201a0>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 08:24:02,540 ERROR  Error while scraping channel info for @MrBeastGaming: 'dict' object has no attribute 'model_dump_json'
2025-01-25 08:24:02,540 ERROR  Error while scraping channel info for @Dream: 'dict' object has no attribute 'model_dump_json'
2025-01-25 08:24:02,542 INFO  Scraping complete for @MrBeastGaming
2025-01-25 08:24:02,542 INFO  Scraping complete for @Dream
2025-01-25 08:24:02,544 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104420e00>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,544 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104420470>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,546 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104420f50>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,546 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104421610>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,548 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1044073b0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,548 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104407650>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,550 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=51664): Max retries exceeded with url: /session/2bbb52b65325103010e69e5d1ee922ec/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104407b00>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 08:24:02,550 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=51634): Max retries exceeded with url: /session/e634d31ac5044156891874464f1c9890/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104407830>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 08:24:02,551 ERROR  Error while scraping channel info for @Sapnap: 'dict' object has no attribute 'model_dump_json'
2025-01-25 08:24:02,551 ERROR  Error while scraping channel info for @GeorgeNotFound: 'dict' object has no attribute 'model_dump_json'
2025-01-25 08:24:02,552 INFO  Scraping complete for @Sapnap
2025-01-25 08:24:02,552 INFO  Scraping complete for @GeorgeNotFound
2025-01-25 08:24:02,554 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10668dc70>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,554 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10668e8a0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,556 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10668d610>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,556 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10668d070>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,558 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1044066f0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,558 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104407920>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,560 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=51664): Max retries exceeded with url: /session/2bbb52b65325103010e69e5d1ee922ec/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1044078f0>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 08:24:02,560 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=51634): Max retries exceeded with url: /session/e634d31ac5044156891874464f1c9890/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1044072f0>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 08:24:02,561 ERROR  Error while scraping channel info for @Technoblade: 'dict' object has no attribute 'model_dump_json'
2025-01-25 08:24:02,561 ERROR  Error while scraping channel info for @TommyInnit: 'dict' object has no attribute 'model_dump_json'
2025-01-25 08:24:02,562 INFO  Scraping complete for @Technoblade
2025-01-25 08:24:02,563 INFO  Scraping complete for @TommyInnit
2025-01-25 08:24:02,564 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104420f50>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,564 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1044202f0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,566 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1044216a0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,566 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1044215b0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,568 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10668ed80>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,568 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10668cf80>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,570 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=51664): Max retries exceeded with url: /session/2bbb52b65325103010e69e5d1ee922ec/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10668d160>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 08:24:02,570 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=51634): Max retries exceeded with url: /session/e634d31ac5044156891874464f1c9890/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10668ffe0>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 08:24:02,571 ERROR  Error while scraping channel info for @WilburSoot: 'dict' object has no attribute 'model_dump_json'
2025-01-25 08:24:02,571 ERROR  Error while scraping channel info for @Tubbo: 'dict' object has no attribute 'model_dump_json'
2025-01-25 08:24:02,572 INFO  Scraping complete for @WilburSoot
2025-01-25 08:24:02,572 INFO  Scraping complete for @Tubbo
2025-01-25 08:24:02,574 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10658f860>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,574 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10668d9a0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,576 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10668f020>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,576 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10668ecc0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,602 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10668d0a0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,602 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10668edb0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,604 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=51634): Max retries exceeded with url: /session/e634d31ac5044156891874464f1c9890/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104421160>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 08:24:02,604 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=51664): Max retries exceeded with url: /session/2bbb52b65325103010e69e5d1ee922ec/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10668e510>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 08:24:02,605 ERROR  Error while scraping channel info for @Stampylonghead: 'dict' object has no attribute 'model_dump_json'
2025-01-25 08:24:02,605 ERROR  Error while scraping channel info for @Ranboo: 'dict' object has no attribute 'model_dump_json'
2025-01-25 08:24:02,607 INFO  Scraping complete for @Stampylonghead
2025-01-25 08:24:02,607 INFO  Scraping complete for @Ranboo
2025-01-25 08:24:02,632 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104420110>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,633 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104405250>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,635 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104407950>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,635 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104407a40>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,637 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10658f770>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,637 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104407140>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,640 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=51664): Max retries exceeded with url: /session/2bbb52b65325103010e69e5d1ee922ec/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10658d3a0>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 08:24:02,640 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=51634): Max retries exceeded with url: /session/e634d31ac5044156891874464f1c9890/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106520050>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 08:24:02,641 ERROR  Error while scraping channel info for @PopularMMOs: 'dict' object has no attribute 'model_dump_json'
2025-01-25 08:24:02,641 ERROR  Error while scraping channel info for @DanTDM: 'dict' object has no attribute 'model_dump_json'
2025-01-25 08:24:02,642 INFO  Scraping complete for @PopularMMOs
2025-01-25 08:24:02,642 INFO  Scraping complete for @DanTDM
2025-01-25 08:24:02,645 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10666a4e0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,645 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106520530>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,647 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10658ff20>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,647 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10658f800>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,650 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104407050>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,650 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104405730>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,652 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=51664): Max retries exceeded with url: /session/2bbb52b65325103010e69e5d1ee922ec/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1044072c0>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 08:24:02,652 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=51634): Max retries exceeded with url: /session/e634d31ac5044156891874464f1c9890/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104421730>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 08:24:02,653 ERROR  Error while scraping channel info for @Jacksepticeye: 'dict' object has no attribute 'model_dump_json'
2025-01-25 08:24:02,653 ERROR  Error while scraping channel info for @Ninja: 'dict' object has no attribute 'model_dump_json'
2025-01-25 08:24:02,654 INFO  Scraping complete for @Jacksepticeye
2025-01-25 08:24:02,655 INFO  Scraping complete for @Ninja
2025-01-25 08:24:02,657 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10668f3b0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,657 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10668dc40>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,659 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10668cf80>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,659 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10668e030>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,661 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106520710>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,661 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10668e9c0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,664 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=51664): Max retries exceeded with url: /session/2bbb52b65325103010e69e5d1ee922ec/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1065209b0>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 08:24:02,664 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=51634): Max retries exceeded with url: /session/e634d31ac5044156891874464f1c9890/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106520830>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 08:24:02,665 ERROR  Error while scraping channel info for @Shroud: 'dict' object has no attribute 'model_dump_json'
2025-01-25 08:24:02,665 ERROR  Error while scraping channel info for @Pokimane: 'dict' object has no attribute 'model_dump_json'
2025-01-25 08:24:02,667 INFO  Scraping complete for @Shroud
2025-01-25 08:24:02,667 INFO  Scraping complete for @Pokimane
